# Generated by Django 2.0.4 on 2018-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_key', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('transtype', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('tradedate', models.DateField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, max_length=150, null=True)),
                ('shareamount', models.IntegerField(blank=True, null=True)),
                ('buyprice', models.FloatField(blank=True, null=True)),
                ('sellprice', models.FloatField(blank=True, null=True)),
                ('commiss', models.FloatField(blank=True, null=True)),
                ('dealsize', models.FloatField(blank=True, null=True)),
                ('dealprice', models.FloatField(blank=True, null=True)),
                ('leadbroker', models.CharField(blank=True, max_length=150, null=True)),
                ('percsellhold', models.FloatField(blank=True, null=True)),
                ('opentraddat', models.DateField(blank=True, null=True)),
                ('vwaptraddat', models.DateField(blank=True, null=True)),
                ('closetraddat', models.DateField(blank=True, null=True)),
                ('prevclose', models.FloatField(blank=True, null=True)),
                ('t2close', models.FloatField(blank=True, null=True)),
                ('t3close', models.FloatField(blank=True, null=True)),
                ('t4close', models.FloatField(blank=True, null=True)),
                ('t5close', models.FloatField(blank=True, null=True)),
                ('spopen', models.FloatField(blank=True, null=True)),
                ('spclose', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
