# Generated by Django 2.0.4 on 2018-05-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180522_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prim_key',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
