# Generated by Django 2.0.4 on 2018-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180522_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
