# Generated by Django 2.0.4 on 2018-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180524_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='matching',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
