# Generated by Django 2.0.6 on 2018-06-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20180603_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='matching_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
